// Servicios comunes en talleres mecánicos para autocompletar
export const SERVICIOS_COMUNES = [
  'Full service con bujías, filtros y aceite, lavar inyectores y cuerpo de aceleración',
  'Full service sin bujías, con filtros y aceite, lavado de motor, inyectores y cuerpo de aceleración',
  'Cambio de aceite y filtro',
  'Cambio de anticongelante',
  'Servicio de verificación incluye derechos',
  'Lavado de motor',
  'Cambio de batería',
  'Lavar y calibrar cuerpo de aceleración',
  'Cambio de líquido de frenos',
  'Recolección a domicilio',
  'Escaneo y diagnóstico',
  'Diagnóstico eléctrico',
  'Limpieza de inyectores en laboratorio',
  'Paquete ABR',
  'Servicio de aire acondicionado',
  'Afinación a transmisión automática',
];

// Refacciones comunes
export const REFACCIONES_COMUNES = [
  'Aceite sintético',
  'Aceite semisintético',
  'Amortiguadores',
  'Anticongelante',
  'Balatas delanteras',
  'Balatas traseras',
  'Batería',
  'Bobina',
  'Bujías',
  'Cables de bujías',
  'Filtro de aceite',
  'Filtro de aire',
  'Filtro de combustible',
  'Líquido de frenos',
  'Pastillas de freno',
  'Terminal de dirección',
];

// Marcas de vehículos comunes en México
export const MARCAS_VEHICULOS = [
  'Acura',
  'Audi',
  'BMW',
  'Buick',
  'Cadillac',
  'Chevrolet',
  'Chrysler',
  'Dodge',
  'Fiat',
  'Ford',
  'GMC',
  'Honda',
  'Hyundai',
  'Infiniti',
  'Jeep',
  'Kia',
  'Land Rover',
  'Lexus',
  'Lincoln',
  'Mazda',
  'Mercedes-Benz',
  'Mini',
  'Mitsubishi',
  'Nissan',
  'Peugeot',
  'Porsche',
  'Ram',
  'Renault',
  'Seat',
  'Subaru',
  'Suzuki',
  'Tesla',
  'Toyota',
  'Volkswagen',
  'Volvo',
];
